name: test docker build (and tag) - [buildpack-deps-plus]

# Controls when the workflow will run
#on: [push]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: docker build buildpack-deps-plus
        run: >
          sh ./build.sh
