name: test docker build (and tag) - [buildpack-deps-plus]

# Controls when the workflow will run
#on: [push]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: >
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}

      - name: docker build buildpack-deps-plus (linux/amd64)
        run: >
          sh ./build.sh "linux/amd64" ""

      - name: docker build buildpack-deps-plus (linux/arm64/v8)
        run: >
          sh ./build.sh "linux/arm64/v8" "arm64v8/"

      - name: docker build buildpack-deps-plus (linux/arm/v7)
        run: >
          sh ./build.sh "linux/arm/v7" "arm32v7/"

      - name: docker build buildpack-deps-plus (linux/s390x)
        run: >
          sh ./build.sh "linux/s390x" "s390x/"

      - name: docker build buildpack-deps-plus (linux/riscv64)
        run: >
          sh ./build.sh "linux/riscv64" "riscv64/"
